create table  BikeShop (
	id INT,
	name VARCHAR(50),
	price VARCHAR(50),
	frame_id INT,
	rings_front INT,
	rings_back INT,
	brakes_front VARCHAR(50),
	brakes_back VARCHAR(50),
	color VARCHAR(50),
	size INT,
	style TEXT,
	diameter INT,
	type TEXT,
	bike_id INT,
	front_tire_id INT,
	back_tire_id INT
);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (1, 'Lotlux', '$1679.35', 373, 1, 1, true, true, 'Yellow', 28, 'dolor', 39, 'justo', 54, 28, 83);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (2, 'Subin', '$1000.99', 784, 2, 2, true, true, 'Maroon', 87, 'sapien', 63, 'mi', 81, 96, 18);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (3, 'Konklab', '$8255.35', 847, 3, 3, false, false, 'Maroon', 12, 'sem', 32, 'nibh', 85, 53, 14);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (4, 'Quo Lux', '$5887.75', 287, 4, 4, true, true, 'Aquamarine', 67, 'tortor', 35, 'luctus', 3, 15, 13);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (5, 'Tresom', '$5103.97', 776, 5, 5, false, false, 'Crimson', 98, 'nulla', 12, 'gravida', 55, 15, 53);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (6, 'Toughjoyfax', '$941.87', 892, 6, 6, true, true, 'Aquamarine', 73, 'nunc', 33, 'eu', 100, 26, 9);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (7, 'Bytecard', '$8995.30', 674, 7, 7, true, true, 'Mauv', 56, 'consequat', 54, 'auctor', 96, 6, 28);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (8, 'Solarbreeze', '$6558.55', 788, 8, 8, false, false, 'Maroon', 77, 'nec', 65, 'adipiscing', 87, 31, 19);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (9, 'Sonsing', '$5273.12', 774, 9, 9, false, true, 'Red', 27, 'cras', 46, 'morbi', 66, 60, 27);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (10, 'Aerified', '$924.64', 331, 10, 10, false, false, 'Purple', 80, 'nulla', 62, 'vestibulum', 91, 32, 95);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (11, 'Aerified', '$817.37', 467, 11, 11, false, false, 'Green', 82, 'urna', 78, 'vel', 22, 48, 98);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (12, 'Stringtough', '$3582.62', 57, 12, 12, true, true, 'Indigo', 63, 'suscipit', 58, 'ligula', 85, 49, 81);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (13, 'It', '$2973.12', 186, 13, 13, true, false, 'Pink', 94, 'erat', 6, 'erat', 22, 61, 73);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (14, 'Bytecard', '$5552.61', 255, 14, 14, true, false, 'Red', 58, 'pede', 68, 'molestie', 71, 11, 83);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (15, 'Zathin', '$2236.19', 649, 15, 15, true, false, 'Crimson', 1, 'sapien', 62, 'mattis', 74, 61, 51);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (16, 'Y-Solowarm', '$5387.17', 715, 16, 16, true, false, 'Pink', 31, 'turpis', 9, 'convallis', 89, 3, 89);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (17, 'Y-Solowarm', '$7931.49', 860, 17, 17, false, true, 'Fuscia', 70, 'congue', 8, 'duis', 62, 80, 14);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (18, 'Bitwolf', '$3589.84', 405, 18, 18, false, false, 'Puce', 78, 'felis', 54, 'nulla', 4, 60, 27);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (19, 'Job', '$5253.48', 357, 19, 19, false, false, 'Crimson', 55, 'at', 50, 'feugiat', 71, 60, 20);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (20, 'Tempsoft', '$2716.04', 183, 20, 20, true, true, 'Indigo', 8, 'blandit', 77, 'in', 28, 42, 27);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (21, 'Holdlamis', '$2089.68', 303, 21, 21, true, true, 'Blue', 59, 'est', 17, 'donec', 31, 29, 33);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (22, 'Flexidy', '$7869.56', 675, 22, 22, false, true, 'Khaki', 19, 'molestie', 27, 'libero', 65, 4, 58);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (23, 'Bytecard', '$4702.82', 474, 23, 23, true, true, 'Yellow', 69, 'vestibulum', 73, 'aliquet', 34, 60, 48);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (24, 'Bamity', '$1531.86', 987, 24, 24, false, false, 'Red', 50, 'habitasse', 72, 'dictumst', 47, 86, 42);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (25, 'Sub-Ex', '$8339.13', 545, 25, 25, true, false, 'Crimson', 25, 'convallis', 79, 'arcu', 72, 15, 17);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (26, 'Bitwolf', '$516.28', 813, 26, 26, true, false, 'Purple', 82, 'a', 4, 'adipiscing', 15, 99, 43);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (27, 'Duobam', '$5009.42', 465, 27, 27, false, true, 'Fuscia', 70, 'donec', 82, 'aenean', 55, 14, 58);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (28, 'Lotstring', '$2755.33', 926, 28, 28, true, false, 'Teal', 36, 'eu', 92, 'pellentesque', 14, 60, 57);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (29, 'Zontrax', '$8391.68', 846, 29, 29, true, true, 'Pink', 47, 'nunc', 89, 'libero', 74, 5, 52);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (30, 'Keylex', '$5027.99', 546, 30, 30, true, false, 'Yellow', 25, 'sit', 3, 'ante', 42, 76, 93);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (31, 'Zoolab', '$7932.93', 573, 31, 31, false, true, 'Teal', 91, 'eu', 67, 'volutpat', 43, 11, 79);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (32, 'Ventosanzap', '$3496.03', 561, 32, 32, true, true, 'Indigo', 53, 'eros', 4, 'lacus', 96, 27, 41);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (33, 'Overhold', '$3918.65', 350, 33, 33, true, false, 'Fuscia', 95, 'urna', 9, 'vestibulum', 95, 69, 34);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (34, 'Ventosanzap', '$8656.81', 456, 34, 34, true, false, 'Violet', 89, 'lacus', 69, 'lacus', 32, 17, 22);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (35, 'Regrant', '$9832.48', 953, 35, 35, true, true, 'Mauv', 24, 'enim', 23, 'quis', 70, 89, 61);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (36, 'Y-Solowarm', '$9495.62', 961, 36, 36, true, false, 'Fuscia', 6, 'morbi', 92, 'elit', 18, 30, 46);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (37, 'Bytecard', '$6902.58', 506, 37, 37, false, false, 'Khaki', 95, 'aliquet', 90, 'congue', 96, 45, 39);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (38, 'Tres-Zap', '$6870.08', 815, 38, 38, false, true, 'Aquamarine', 32, 'luctus', 43, 'donec', 86, 43, 83);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (39, 'Sub-Ex', '$8279.28', 996, 39, 39, true, false, 'Fuscia', 29, 'nam', 99, 'amet', 90, 71, 15);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (40, 'Span', '$4249.87', 60, 40, 40, false, false, 'Khaki', 39, 'hac', 93, 'morbi', 60, 4, 47);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (41, 'Flowdesk', '$9278.93', 958, 41, 41, false, false, 'Yellow', 93, 'maecenas', 100, 'cubilia', 74, 34, 77);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (42, 'Regrant', '$2041.65', 199, 42, 42, true, false, 'Maroon', 92, 'est', 95, 'nulla', 6, 47, 81);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (43, 'Zaam-Dox', '$9180.35', 145, 43, 43, false, false, 'Green', 86, 'quisque', 86, 'in', 85, 75, 23);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (44, 'Otcom', '$7512.22', 793, 44, 44, false, false, 'Goldenrod', 22, 'vitae', 21, 'nulla', 20, 97, 49);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (45, 'Treeflex', '$8087.54', 416, 45, 45, true, true, 'Blue', 63, 'eget', 92, 'at', 7, 70, 35);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (46, 'Bytecard', '$1166.94', 860, 46, 46, true, true, 'Purple', 38, 'consequat', 54, 'tortor', 98, 39, 68);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (47, 'Fintone', '$54.12', 640, 47, 47, true, true, 'Pink', 98, 'cubilia', 32, 'eget', 77, 60, 54);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (48, 'Prodder', '$2123.97', 379, 48, 48, true, true, 'Violet', 96, 'donec', 83, 'elit', 80, 10, 73);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (49, 'Sub-Ex', '$8380.13', 694, 49, 49, false, true, 'Purple', 72, 'sapien', 17, 'a', 34, 76, 47);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (50, 'Lotstring', '$7419.50', 296, 50, 50, true, true, 'Aquamarine', 26, 'id', 44, 'volutpat', 47, 2, 33);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (51, 'Temp', '$6436.94', 282, 51, 51, true, false, 'Red', 92, 'eros', 32, 'quis', 46, 21, 99);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (52, 'Gembucket', '$3506.49', 925, 52, 52, false, false, 'Blue', 44, 'leo', 12, 'donec', 70, 65, 13);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (53, 'Namfix', '$9789.20', 459, 53, 53, true, true, 'Violet', 30, 'molestie', 67, 'at', 58, 62, 18);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (54, 'Transcof', '$6661.06', 381, 54, 54, true, true, 'Teal', 34, 'nisi', 49, 'sit', 34, 6, 10);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (55, 'Flexidy', '$8304.50', 968, 55, 55, false, true, 'Maroon', 60, 'a', 37, 'molestie', 86, 95, 28);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (56, 'Namfix', '$355.90', 362, 56, 56, true, true, 'Indigo', 1, 'dolor', 91, 'nulla', 86, 65, 56);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (57, 'Job', '$9149.34', 170, 57, 57, true, false, 'Mauv', 70, 'sed', 63, 'ullamcorper', 9, 41, 32);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (58, 'Veribet', '$6826.96', 89, 58, 58, true, true, 'Pink', 53, 'primis', 85, 'mauris', 27, 96, 35);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (59, 'Vagram', '$3486.87', 46, 59, 59, false, false, 'Teal', 95, 'et', 45, 'non', 44, 81, 9);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (60, 'Bitwolf', '$2278.33', 742, 60, 60, true, false, 'Blue', 34, 'amet', 50, 'habitasse', 25, 59, 67);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (61, 'Y-find', '$2827.21', 983, 61, 61, true, true, 'Crimson', 36, 'semper', 76, 'quisque', 33, 35, 57);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (62, 'Fixflex', '$8232.20', 633, 62, 62, true, true, 'Green', 93, 'arcu', 100, 'nam', 96, 95, 48);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (63, 'Toughjoyfax', '$3030.29', 766, 63, 63, false, true, 'Purple', 40, 'primis', 79, 'sed', 20, 85, 42);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (64, 'Tampflex', '$7973.03', 345, 64, 64, true, true, 'Yellow', 35, 'nunc', 14, 'congue', 14, 8, 10);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (65, 'Opela', '$1003.25', 1, 65, 65, false, false, 'Mauv', 1, 'faucibus', 88, 'parturient', 54, 32, 93);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (66, 'Sub-Ex', '$6237.16', 327, 66, 66, true, true, 'Turquoise', 18, 'aenean', 94, 'ligula', 33, 40, 67);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (67, 'Holdlamis', '$5902.88', 991, 67, 67, true, true, 'Crimson', 27, 'venenatis', 32, 'donec', 38, 92, 76);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (68, 'Regrant', '$8817.91', 481, 68, 68, false, false, 'Red', 98, 'imperdiet', 20, 'quisque', 100, 12, 85);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (69, 'Veribet', '$6447.76', 69, 69, 69, true, false, 'Fuscia', 42, 'nisl', 12, 'in', 13, 53, 47);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (70, 'Cardify', '$3454.25', 157, 70, 70, true, true, 'Orange', 80, 'mattis', 95, 'orci', 44, 14, 30);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (71, 'Hatity', '$1978.65', 744, 71, 71, false, true, 'Mauv', 51, 'nulla', 35, 'in', 3, 50, 6);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (72, 'Sonair', '$4597.60', 121, 72, 72, false, false, 'Aquamarine', 53, 'etiam', 33, 'nisi', 97, 71, 62);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (73, 'Fixflex', '$5772.49', 758, 73, 73, false, false, 'Indigo', 93, 'sed', 12, 'maecenas', 15, 40, 87);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (74, 'Ronstring', '$7586.41', 131, 74, 74, true, true, 'Red', 46, 'eu', 97, 'odio', 49, 18, 99);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (75, 'Sub-Ex', '$7099.48', 214, 75, 75, false, true, 'Aquamarine', 32, 'nisl', 55, 'dui', 54, 24, 49);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (76, 'Cardguard', '$9587.19', 387, 76, 76, false, false, 'Goldenrod', 62, 'tristique', 87, 'orci', 86, 89, 41);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (77, 'Job', '$9113.36', 448, 77, 77, true, false, 'Maroon', 61, 'eu', 15, 'dolor', 67, 86, 19);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (78, 'Wrapsafe', '$9012.00', 912, 78, 78, true, true, 'Blue', 76, 'quam', 57, 'nisi', 89, 4, 36);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (79, 'Flexidy', '$8394.09', 51, 79, 79, false, false, 'Turquoise', 96, 'sit', 72, 'vestibulum', 48, 91, 15);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (80, 'Opela', '$2265.36', 372, 80, 80, true, false, 'Orange', 58, 'in', 78, 'arcu', 3, 44, 18);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (81, 'Voltsillam', '$6786.84', 36, 81, 81, true, true, 'Purple', 63, 'ut', 22, 'eu', 97, 67, 96);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (82, 'Ventosanzap', '$4942.94', 708, 82, 82, true, true, 'Violet', 40, 'a', 31, 'lacus', 71, 52, 70);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (83, 'Otcom', '$2270.66', 756, 83, 83, true, true, 'Violet', 20, 'rhoncus', 16, 'integer', 77, 64, 32);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (84, 'Biodex', '$4165.05', 789, 84, 84, true, false, 'Teal', 95, 'id', 2, 'odio', 56, 60, 47);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (85, 'Hatity', '$4740.92', 982, 85, 85, false, true, 'Violet', 60, 'id', 88, 'leo', 83, 24, 93);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (86, 'Flexidy', '$7735.75', 318, 86, 86, true, false, 'Crimson', 32, 'quam', 10, 'amet', 20, 34, 52);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (87, 'Tin', '$1805.56', 879, 87, 87, false, true, 'Maroon', 82, 'pulvinar', 28, 'mauris', 77, 59, 91);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (88, 'Kanlam', '$7732.15', 60, 88, 88, false, true, 'Orange', 84, 'libero', 58, 'vehicula', 71, 77, 4);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (89, 'Vagram', '$2119.37', 944, 89, 89, true, false, 'Aquamarine', 72, 'nulla', 43, 'cras', 38, 53, 35);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (90, 'Stim', '$5869.08', 270, 90, 90, false, true, 'Green', 29, 'quis', 74, 'odio', 64, 24, 77);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (91, 'Span', '$3821.72', 299, 91, 91, true, false, 'Puce', 61, 'ac', 43, 'id', 6, 92, 92);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (92, 'Trippledex', '$4451.33', 684, 92, 92, true, true, 'Green', 62, 'magnis', 66, 'hac', 13, 86, 31);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (93, 'Zontrax', '$6062.02', 837, 93, 93, true, true, 'Indigo', 71, 'nisi', 58, 'iaculis', 18, 23, 26);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (94, 'Stronghold', '$6830.83', 633, 94, 94, true, false, 'Violet', 73, 'elit', 39, 'cras', 44, 81, 54);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (95, 'Cardify', '$1725.42', 762, 95, 95, false, false, 'Purple', 89, 'nam', 47, 'ligula', 68, 38, 49);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (96, 'Zontrax', '$7983.54', 322, 96, 96, false, false, 'Blue', 35, 'eleifend', 20, 'nullam', 99, 46, 17);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (97, 'Latlux', '$9796.61', 715, 97, 97, false, false, 'Yellow', 99, 'dictumst', 73, 'nulla', 87, 75, 51);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (98, 'Y-find', '$2203.18', 416, 98, 98, false, false, 'Puce', 47, 'eros', 39, 'ante', 61, 31, 69);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (99, 'Voltsillam', '$7039.66', 168, 99, 99, false, true, 'Turquoise', 35, 'eros', 10, 'lobortis', 56, 44, 62);
insert into BikeShop (id, name, price, frame_id, rings_front, rings_back, brakes_front, brakes_back, color, size, style, diameter, type, bike_id, front_tire_id, back_tire_id) values (100, 'Alphazap', '$4196.08', 370, 100, 100, true, false, 'Purple', 82, 'lacinia', 66, 'id', 95, 43, 78);
